### ISSUE TITLE
Fix workflow of README file.

### ISSUE THREAD

**Issue by washingtonsk8** [verlab/SemanticFastForward_ECCVW_2016#1]
We cannot set the <Num_non_semantic_Frames> and <Num_semantic_Frames> easily via README. You have to add the [~, Tns, Ts] = GetSemanticRanges('../example_face_extracted.mat'); function present in Example.m file to it.

**Comment by michelmelosilva** [comment]
![epic eccvw_flowchart](https://user-images.githubusercontent.com/23279754/38369324-cf30af52-38bd-11e8-9314-67144f134f5c.jpg)
